# FlexOS pacman.conf

[options]
HoldPkg = pacman glibc
Architecture = auto
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# Arch Linux CN (optional, uncomment if needed)
# [archlinuxcn]
# Server = https://repo.archlinux.cn/$arch
