[greeter]
background = /usr/share/backgrounds/flexos/flex-wallpaper.svg
theme-name = FlexOS
icon-theme-name = Papirus
font-name = Cantarell 11
xft-antialias = true
xft-hintstyle = hintfull
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %H:%M
position = 50%,center 50%,center
screensaver-timeout = 30
