# FlexOS Calamares - Bootloader Module (GRUB)
---
bootloader:
  installer: grub
  efi: true
  bios: true
  efiBootloaderId: "flexos"
  grubInstall: grub-install
  grubMkconfig: grub-mkconfig
  grubCfg: /boot/grub/grub.cfg
  efiDirectory: "/boot"
