# FlexOS Calamares - Keyboard Module
---
keyboardModels:
  pc104: "PC 104-key"
  pc105: "PC 105-key"
  macbook78: "MacBook"
  macbook79: "MacBook (Intl)"
xf86ConfDir: "/usr/share/X11/xkb/rules/base.lst"
