# FlexOS Calamares - Mount Module
---
extraMounts:
  - filesystem: proc
    mountPoint: /proc
    targetSystem: true
  - filesystem: sysfs
    mountPoint: /sys
    targetSystem: true
  - filesystem: devtmpfs
    mountPoint: /dev
    targetSystem: true
  - filesystem: run
    mountPoint: /run
    targetSystem: true
