# FlexOS Calamares - Partition Module
---
defaultFileSystemType: "ext4"
drawNestedPartitions: false
alwaysShowPartitionLabels: true
enableLuks: true
enableLuksPopup: true
eraseSwapLarge: true
allowPartitionLabels: true
initialPartitioningChoice: "none"
defaultPartitioningChoice: "none"
