# FlexOS Calamares - Unpackfs Module
# Désarchive l'image squashfs live vers la cible
---
unpack:
  - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
    sourceType: "file"
