# FlexOS Calamares - Users Module
---
defaultGroups:
  - lp
  - wheel
  - network
  - video
  - audio
  - optical
  - storage
  - scanner
  - power
  - users
  - input
  - docker
  - kvm
  - libvirt
autologinGroup: true
doAutologin: true
doReusePassword: true
setRootPassword: false
shell: /bin/bash
