# FlexOS Calamares - Main Settings
---
modules-search: [ /etc/calamares/modules ]

sequence:
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
- always:
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - initcpiocfg
    - grubcfg
    - bootloader
    - networkcfg
    - hwclock
    - services-systemd
    - displaymanager
    - users
    - chrootcfg
- show:
    - finished

branding: flexos

prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
quit-at-end: false

web:
  url: ""
